### ISSUE TITLE
How to solomagic1?

### ISSUE THREAD

**Issue by savili** [aleixpol/solomagic#4]
I tried solomagic1.py, but I can't figure out (yet) how to use it.
This is the result I keep getting:

 File "solomagic1.py", line 4, in <module>
    parser = argparse.ArgumentParser()
NameError: name 'argparse' is not defined

I think I need monkey instructions again for solomagic1.py

**Comment by aleixpol** [comment]
Please, see if it's fixed.
Weird because it worked here...
